### PR TITLE
black version changed, precommit updated

### PR DESCRIPTION
**Pull request by jwmcode**

### CODE REVIEW

**Review by Bassel-Ghazali — COMMENTED** [review]
Were the changes to the versions in the yaml file manually made, or are they a result of the change made to the black version in the pipfile?

**Review by stefan-anmut — APPROVED** [review]
looks good, thanks james

**Review by Bassel-Ghazali — APPROVED** [review]
lgtm2!

**Comment by stefan-anmut** [comment]
> Were the changes to the versions in the yaml file manually made, or are they a result of the change made to the black version in the pipfile?

the changes were made by running `pre-commit autoupdate` in the folder where the [.pre-commit-config.yaml](https://github.com/anmut-consulting/pipenv-cookiecutter/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/.pre-commit-config.yaml) file exists @Bassel-Ghazali

**Pull request merged**
